insert into item (id, name , price, quantity, category) values (1, 'Milk', 0.5, 5, 'Dairy');
insert into item (id, name , price, quantity, category) values (2, 'Cheese', 5.45, 15, 'Dairy');
insert into item (id, name , price, quantity, category) values (3, 'Carrots', 4.84, 20, 'Vegetable');
insert into item (id, name , price, quantity, category) values (4, 'Yogurt', 1.19, 14, 'Dairy');
insert into item (id, name , price, quantity, category) values (5, 'Pasta', 1.25, 11, 'Grains');
insert into item (id, name , price, quantity, category) values (6, 'Wheat', 0.75, 10, 'Grains');
insert into item (id, name , price, quantity, category) values (7, 'White Rice', 1.5, 15, 'Grains');
insert into item (id, name , price, quantity, category) values (8, 'Eggs', 0.15, 100, 'Poultry');
insert into item (id, name , price, quantity, category) values (9, 'Beef', 3.78, 11, 'Meat');
insert into item (id, name , price, quantity, category) values (10, 'Chicken', 2.50, 22, 'Meat');